### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jknutson** [jknutson/pico-weatherstation-c#2]
running list of TODOs. should probably be broken out to individuals before working on them.

# Project
- [x] upload photos of hardware
- [ ] create wiring diagrams
- [x] post to [forum](https://www.raspberrypi.org/forums/viewtopic.php?f=144&t=314697)
- [ ] add "getting started" section to readme
- [ ] add "bill of materials" section to readme
- [ ] versioning
- [ ] split pico code & console reader/mq emitter

# Hardware
- [x] #8
- [ ] add barometric pressure & air quality sensor
- [ ] move rain gauge move to pico
- [x] move station to garden
- [ ] (tangent) integrate solar ESP with Original Pi
  - lux/charge current could tie into time of day & conditions
- [x] (tangent) upgrade Original Pi (more USB)
- [x] setup Pico SWD

# Software
### Pico/C
- [ ] tests!
- [ ] publish periodic summary/stats (DHT22 CRC mismatch count, cb_counts)
- [x] #11
  - gusts
  - direction names
- [ ] improve debounce
  - [this](https://github.com/GitJer/Some_RPI-Pico_stuff/tree/main/Button-debouncer) might be interesting (PIO debounce)
- [ ] dewpoint & heat index
- [ ] #9
- [ ] additional output formats
  - Human Readable (Pretty Print)
  - UrlEncode
  - Tab/Comma Separated
  - Other common datalogging format?
### Raspberry Pi
- [ ] integrate with dump1090?
  - upgrade Pi for more USB, or just listen to port 30003 for raw flight data
- [x] pyconsole.py - rewrite in Golang
### UI
- [ ] improve wind direction image assets (dark mode)
- [ ] letsencrypt & vanity domain for Grafana
